modLoader="javafml"
loaderVersion="[33,)"
license="MIT"
issueTrackerURL="https://github.com/Ephys/CookieCore/issues"
[[mods]]
modId="cookiecore"
version="${version}"
displayName="CookieCore"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/222908"
displayURL="https://github.com/Ephys/CookieCore"
logoFile="logo.png"
authors="ephys, eizhfox"
description='''
Config registration utilities
NBT Utilities
'''
[[dependencies.cookiecore]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cookiecore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"
